env:
  browser: true
  es2021: true
extends:
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  react/react-in-jsx-scope: 'off'
  import/extensions: 'off'
  react/jsx-props-no-spreading: 'off'
  jsx-a11y/tabindex-no-positive: 'off'
  import/prefer-default-export: 'off'
  react/destructuring-assignment: 'off'
  react-hooks/exhaustive-deps: 'off'
  react/jsx-no-useless-fragment: 'off'
  react/function-component-definition: 'off'
  jsx-a11y/label-has-associated-control: 'off'
  prettier/prettier:
    - 'error'
    - endOfLine: 'auto'